# Generated by Django 4.1 on 2022-08-23 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-pub_date',)},
        ),
    ]
